### ISSUE TITLE
Cpp version

### ISSUE THREAD

**Issue by eavcodes** [Maickonn/AllaKore_Remote#1]
Nice project and initiative! There is a Cpp Builder 10 Seattle version?

**Comment by maickonn** [comment]
> Nice project and initiative! There is a Cpp Builder 10 Seattle version?

Thanks, @emilianoveiga !
Unfortunately there is no version for CPP Builder.

**Comment by d0k1-tech** [comment]
@emilianoveiga

This is a work for researching and studies of sockets.

>> Postarei um README.md e ficará mais claro. Trate como erro resolvido, porque isso não é um erro.
>>> I ll be post a new README.md and the finality; This explaining better about and why this project exists. Can you set this issue thread how it's ok. Ok?
we'll bee so gratified!
---
## Tip:
All work is, comunication with others softwares, humans, protocols... Abstracion is free!

REMEMBERING NOTE: if it alert Virus, don't run. Before: CHECK IF IS AN VIRUS! <- Sorry this uppercase how much peoples report that. This repo. is open and free to concern, abstraction and studie!

Any breach of app don't being a finnest treatament, and some don't has. BECAUSE IS TO FINALITY OF STUDIES. 

Any damaged or harmful app derived which use this code is totally. Is be totally!  * $$100 * 100 times$$ unmotivated and can't be regulated, or predict with by Authors. The way which is used to developing. HEADERS of software, including in compiling. It's assign your own risk to you and beings a proof to idiot.

## Tip 2:
> Develop Application in CPP Builder! Don't has a code it's not an #Issue

And you be being an aewwwssoommeeeee man!
---
Enjoy the travel! clone repository and be a spaceship man!

**Comment by eavcodes** [comment]
Thanks for information. Regards
